
# Setup

title:            jrmas.github.io
url:              https://jrmas.github.io
baseurl:          /

author:
  name:           'Jordi Mas'
  url:            https://github.com/jrmas

paginate:         5
